package com.nh.oms.model.oms;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsBaseProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.iid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product._status
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.object_type
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Integer objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.typeid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.code
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.name
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.ename
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.shortname
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.market_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.member_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private BigDecimal memberPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.tax_rate
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Double taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.shortcontent
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String shortcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.description
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.sort
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.weight
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.unit
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.remark
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.create_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.create_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.update_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_base_product.update_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private String updateUserId;

    private String genericName;

    public String getGenericName() {
        return genericName;
    }

    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_base_product
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.iid
     *
     * @return the value of oms_base_product.iid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.iid
     *
     * @param iid the value for oms_base_product.iid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.id
     *
     * @return the value of oms_base_product.id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.id
     *
     * @param id the value for oms_base_product.id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product._status
     *
     * @return the value of oms_base_product._status
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product._status
     *
     * @param status the value for oms_base_product._status
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.object_type
     *
     * @return the value of oms_base_product.object_type
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Integer getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.object_type
     *
     * @param objectType the value for oms_base_product.object_type
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.typeid
     *
     * @return the value of oms_base_product.typeid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.typeid
     *
     * @param typeid the value for oms_base_product.typeid
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.code
     *
     * @return the value of oms_base_product.code
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.code
     *
     * @param code the value for oms_base_product.code
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.name
     *
     * @return the value of oms_base_product.name
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.name
     *
     * @param name the value for oms_base_product.name
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.ename
     *
     * @return the value of oms_base_product.ename
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.ename
     *
     * @param ename the value for oms_base_product.ename
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.shortname
     *
     * @return the value of oms_base_product.shortname
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.shortname
     *
     * @param shortname the value for oms_base_product.shortname
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.market_price
     *
     * @return the value of oms_base_product.market_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.market_price
     *
     * @param marketPrice the value for oms_base_product.market_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.member_price
     *
     * @return the value of oms_base_product.member_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public BigDecimal getMemberPrice() {
        return memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.member_price
     *
     * @param memberPrice the value for oms_base_product.member_price
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setMemberPrice(BigDecimal memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.tax_rate
     *
     * @return the value of oms_base_product.tax_rate
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Double getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.tax_rate
     *
     * @param taxRate the value for oms_base_product.tax_rate
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.shortcontent
     *
     * @return the value of oms_base_product.shortcontent
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getShortcontent() {
        return shortcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.shortcontent
     *
     * @param shortcontent the value for oms_base_product.shortcontent
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setShortcontent(String shortcontent) {
        this.shortcontent = shortcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.description
     *
     * @return the value of oms_base_product.description
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.description
     *
     * @param description the value for oms_base_product.description
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.sort
     *
     * @return the value of oms_base_product.sort
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.sort
     *
     * @param sort the value for oms_base_product.sort
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.weight
     *
     * @return the value of oms_base_product.weight
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.weight
     *
     * @param weight the value for oms_base_product.weight
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.unit
     *
     * @return the value of oms_base_product.unit
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.unit
     *
     * @param unit the value for oms_base_product.unit
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.remark
     *
     * @return the value of oms_base_product.remark
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.remark
     *
     * @param remark the value for oms_base_product.remark
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.create_time
     *
     * @return the value of oms_base_product.create_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.create_time
     *
     * @param createTime the value for oms_base_product.create_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.create_user_id
     *
     * @return the value of oms_base_product.create_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.create_user_id
     *
     * @param createUserId the value for oms_base_product.create_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.update_time
     *
     * @return the value of oms_base_product.update_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.update_time
     *
     * @param updateTime the value for oms_base_product.update_time
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_base_product.update_user_id
     *
     * @return the value of oms_base_product.update_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_base_product.update_user_id
     *
     * @param updateUserId the value for oms_base_product.update_user_id
     *
     * @mbggenerated Thu Nov 08 13:14:29 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }
}