package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;

public class OmsChannelGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_channel_group.pid
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_channel_group.group_name
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_channel_group.is_enable
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_channel_group.create_time
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_channel_group.remark
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_channel_group.pid
     *
     * @return the value of oms_channel_group.pid
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_channel_group.pid
     *
     * @param pid the value for oms_channel_group.pid
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_channel_group.group_name
     *
     * @return the value of oms_channel_group.group_name
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_channel_group.group_name
     *
     * @param groupName the value for oms_channel_group.group_name
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_channel_group.is_enable
     *
     * @return the value of oms_channel_group.is_enable
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_channel_group.is_enable
     *
     * @param isEnable the value for oms_channel_group.is_enable
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_channel_group.create_time
     *
     * @return the value of oms_channel_group.create_time
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_channel_group.create_time
     *
     * @param createTime the value for oms_channel_group.create_time
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_channel_group.remark
     *
     * @return the value of oms_channel_group.remark
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_channel_group.remark
     *
     * @param remark the value for oms_channel_group.remark
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}