package com.nh.oms.model.oms;

import java.io.Serializable;

public class OmsComponent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_component.iid
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_component.product_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_component.component_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private String componentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_component.component_name
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private String componentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_component.object_type
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private Integer objectType;

    /**
     * 是否赠品字段
     */
    private int isFreebie;

    public int getIsFreebie() {
        return isFreebie;
    }

    public void setIsFreebie(int isFreebie) {
        this.isFreebie = isFreebie;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_component
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_component.iid
     *
     * @return the value of oms_component.iid
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_component.iid
     *
     * @param iid the value for oms_component.iid
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public void setIid(long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_component.product_code
     *
     * @return the value of oms_component.product_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_component.product_code
     *
     * @param productCode the value for oms_component.product_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_component.component_code
     *
     * @return the value of oms_component.component_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public String getComponentCode() {
        return componentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_component.component_code
     *
     * @param componentCode the value for oms_component.component_code
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public void setComponentCode(String componentCode) {
        this.componentCode = componentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_component.component_name
     *
     * @return the value of oms_component.component_name
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_component.component_name
     *
     * @param componentName the value for oms_component.component_name
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_component.object_type
     *
     * @return the value of oms_component.object_type
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public Integer getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_component.object_type
     *
     * @param objectType the value for oms_component.object_type
     *
     * @mbggenerated Tue Nov 06 19:45:41 CST 2018
     */
    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }
}