package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;

public class OmsOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.iid
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_parent_id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String orderParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_parent_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String orderParentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.out_trade_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_state
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.insure
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String insure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.insure_relation
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String insureRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.policy_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.detected_person
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String detectedPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.sex
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.birthday
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.certificate_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.certificate_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.detected_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String detectedPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.policy_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String policyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.policy_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String policyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String receiverAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String orderSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.box_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String boxSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.box_back_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String boxBackSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_is_paper
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportIsPaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_is_business
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportIsBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportReceiverAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportReceiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportReceiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportReceiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.report_notice
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String reportNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.create_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.update_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.current_index_sort
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Integer currentIndexSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.address_lock
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String addressLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.address_clear
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String addressClear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.channel_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.channel_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.term_enable
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String termEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.term_days
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Integer termDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.term_date
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Date termDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.is_modify
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String isModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.is_package
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String isPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.reject_times
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private Integer rejectTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.laboratory
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String laboratory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.remark
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.iid
     *
     * @return the value of oms_order.iid
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.iid
     *
     * @param iid the value for oms_order.iid
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.id
     *
     * @return the value of oms_order.id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.id
     *
     * @param id the value for oms_order.id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_no
     *
     * @return the value of oms_order.order_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_no
     *
     * @param orderNo the value for oms_order.order_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_parent_id
     *
     * @return the value of oms_order.order_parent_id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOrderParentId() {
        return orderParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_parent_id
     *
     * @param orderParentId the value for oms_order.order_parent_id
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOrderParentId(String orderParentId) {
        this.orderParentId = orderParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_parent_no
     *
     * @return the value of oms_order.order_parent_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOrderParentNo() {
        return orderParentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_parent_no
     *
     * @param orderParentNo the value for oms_order.order_parent_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOrderParentNo(String orderParentNo) {
        this.orderParentNo = orderParentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.out_trade_no
     *
     * @return the value of oms_order.out_trade_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.out_trade_no
     *
     * @param outTradeNo the value for oms_order.out_trade_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_state
     *
     * @return the value of oms_order.order_state
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_state
     *
     * @param orderState the value for oms_order.order_state
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.insure
     *
     * @return the value of oms_order.insure
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getInsure() {
        return insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.insure
     *
     * @param insure the value for oms_order.insure
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setInsure(String insure) {
        this.insure = insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.insure_relation
     *
     * @return the value of oms_order.insure_relation
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getInsureRelation() {
        return insureRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.insure_relation
     *
     * @param insureRelation the value for oms_order.insure_relation
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setInsureRelation(String insureRelation) {
        this.insureRelation = insureRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.policy_no
     *
     * @return the value of oms_order.policy_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.policy_no
     *
     * @param policyNo the value for oms_order.policy_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.detected_person
     *
     * @return the value of oms_order.detected_person
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getDetectedPerson() {
        return detectedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.detected_person
     *
     * @param detectedPerson the value for oms_order.detected_person
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setDetectedPerson(String detectedPerson) {
        this.detectedPerson = detectedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.sex
     *
     * @return the value of oms_order.sex
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.sex
     *
     * @param sex the value for oms_order.sex
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.birthday
     *
     * @return the value of oms_order.birthday
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.birthday
     *
     * @param birthday the value for oms_order.birthday
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.certificate_type
     *
     * @return the value of oms_order.certificate_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.certificate_type
     *
     * @param certificateType the value for oms_order.certificate_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.certificate_no
     *
     * @return the value of oms_order.certificate_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.certificate_no
     *
     * @param certificateNo the value for oms_order.certificate_no
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.detected_phone
     *
     * @return the value of oms_order.detected_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getDetectedPhone() {
        return detectedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.detected_phone
     *
     * @param detectedPhone the value for oms_order.detected_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setDetectedPhone(String detectedPhone) {
        this.detectedPhone = detectedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.policy_code
     *
     * @return the value of oms_order.policy_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getPolicyCode() {
        return policyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.policy_code
     *
     * @param policyCode the value for oms_order.policy_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setPolicyCode(String policyCode) {
        this.policyCode = policyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.policy_name
     *
     * @return the value of oms_order.policy_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.policy_name
     *
     * @param policyName the value for oms_order.policy_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_area_code
     *
     * @return the value of oms_order.receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReceiverAreaCode() {
        return receiverAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_area_code
     *
     * @param receiverAreaCode the value for oms_order.receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReceiverAreaCode(String receiverAreaCode) {
        this.receiverAreaCode = receiverAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_name
     *
     * @return the value of oms_order.receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_name
     *
     * @param receiverName the value for oms_order.receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_address
     *
     * @return the value of oms_order.receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_address
     *
     * @param receiverAddress the value for oms_order.receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_phone
     *
     * @return the value of oms_order.receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_phone
     *
     * @param receiverPhone the value for oms_order.receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_sms
     *
     * @return the value of oms_order.order_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getOrderSms() {
        return orderSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_sms
     *
     * @param orderSms the value for oms_order.order_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setOrderSms(String orderSms) {
        this.orderSms = orderSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.box_sms
     *
     * @return the value of oms_order.box_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getBoxSms() {
        return boxSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.box_sms
     *
     * @param boxSms the value for oms_order.box_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setBoxSms(String boxSms) {
        this.boxSms = boxSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.box_back_sms
     *
     * @return the value of oms_order.box_back_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getBoxBackSms() {
        return boxBackSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.box_back_sms
     *
     * @param boxBackSms the value for oms_order.box_back_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setBoxBackSms(String boxBackSms) {
        this.boxBackSms = boxBackSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_sms
     *
     * @return the value of oms_order.report_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportSms() {
        return reportSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_sms
     *
     * @param reportSms the value for oms_order.report_sms
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportSms(String reportSms) {
        this.reportSms = reportSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_is_paper
     *
     * @return the value of oms_order.report_is_paper
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportIsPaper() {
        return reportIsPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_is_paper
     *
     * @param reportIsPaper the value for oms_order.report_is_paper
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportIsPaper(String reportIsPaper) {
        this.reportIsPaper = reportIsPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_is_business
     *
     * @return the value of oms_order.report_is_business
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportIsBusiness() {
        return reportIsBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_is_business
     *
     * @param reportIsBusiness the value for oms_order.report_is_business
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportIsBusiness(String reportIsBusiness) {
        this.reportIsBusiness = reportIsBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_receiver_area_code
     *
     * @return the value of oms_order.report_receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportReceiverAreaCode() {
        return reportReceiverAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_receiver_area_code
     *
     * @param reportReceiverAreaCode the value for oms_order.report_receiver_area_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportReceiverAreaCode(String reportReceiverAreaCode) {
        this.reportReceiverAreaCode = reportReceiverAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_receiver_name
     *
     * @return the value of oms_order.report_receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportReceiverName() {
        return reportReceiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_receiver_name
     *
     * @param reportReceiverName the value for oms_order.report_receiver_name
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportReceiverName(String reportReceiverName) {
        this.reportReceiverName = reportReceiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_receiver_phone
     *
     * @return the value of oms_order.report_receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportReceiverPhone() {
        return reportReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_receiver_phone
     *
     * @param reportReceiverPhone the value for oms_order.report_receiver_phone
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportReceiverPhone(String reportReceiverPhone) {
        this.reportReceiverPhone = reportReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_receiver_address
     *
     * @return the value of oms_order.report_receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportReceiverAddress() {
        return reportReceiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_receiver_address
     *
     * @param reportReceiverAddress the value for oms_order.report_receiver_address
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportReceiverAddress(String reportReceiverAddress) {
        this.reportReceiverAddress = reportReceiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.report_notice
     *
     * @return the value of oms_order.report_notice
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getReportNotice() {
        return reportNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.report_notice
     *
     * @param reportNotice the value for oms_order.report_notice
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setReportNotice(String reportNotice) {
        this.reportNotice = reportNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.create_time
     *
     * @return the value of oms_order.create_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.create_time
     *
     * @param createTime the value for oms_order.create_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.update_time
     *
     * @return the value of oms_order.update_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.update_time
     *
     * @param updateTime the value for oms_order.update_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_time
     *
     * @return the value of oms_order.pay_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_time
     *
     * @param payTime the value for oms_order.pay_time
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.current_index_sort
     *
     * @return the value of oms_order.current_index_sort
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Integer getCurrentIndexSort() {
        return currentIndexSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.current_index_sort
     *
     * @param currentIndexSort the value for oms_order.current_index_sort
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setCurrentIndexSort(Integer currentIndexSort) {
        this.currentIndexSort = currentIndexSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.address_lock
     *
     * @return the value of oms_order.address_lock
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getAddressLock() {
        return addressLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.address_lock
     *
     * @param addressLock the value for oms_order.address_lock
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setAddressLock(String addressLock) {
        this.addressLock = addressLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.address_clear
     *
     * @return the value of oms_order.address_clear
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getAddressClear() {
        return addressClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.address_clear
     *
     * @param addressClear the value for oms_order.address_clear
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setAddressClear(String addressClear) {
        this.addressClear = addressClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.channel_code
     *
     * @return the value of oms_order.channel_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.channel_code
     *
     * @param channelCode the value for oms_order.channel_code
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.channel_type
     *
     * @return the value of oms_order.channel_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.channel_type
     *
     * @param channelType the value for oms_order.channel_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_type
     *
     * @return the value of oms_order.delivery_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_type
     *
     * @param deliveryType the value for oms_order.delivery_type
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.term_enable
     *
     * @return the value of oms_order.term_enable
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getTermEnable() {
        return termEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.term_enable
     *
     * @param termEnable the value for oms_order.term_enable
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setTermEnable(String termEnable) {
        this.termEnable = termEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.term_days
     *
     * @return the value of oms_order.term_days
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Integer getTermDays() {
        return termDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.term_days
     *
     * @param termDays the value for oms_order.term_days
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setTermDays(Integer termDays) {
        this.termDays = termDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.term_date
     *
     * @return the value of oms_order.term_date
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Date getTermDate() {
        return termDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.term_date
     *
     * @param termDate the value for oms_order.term_date
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.is_modify
     *
     * @return the value of oms_order.is_modify
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getIsModify() {
        return isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.is_modify
     *
     * @param isModify the value for oms_order.is_modify
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setIsModify(String isModify) {
        this.isModify = isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.is_package
     *
     * @return the value of oms_order.is_package
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.is_package
     *
     * @param isPackage the value for oms_order.is_package
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setIsPackage(String isPackage) {
        this.isPackage = isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.reject_times
     *
     * @return the value of oms_order.reject_times
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public Integer getRejectTimes() {
        return rejectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.reject_times
     *
     * @param rejectTimes the value for oms_order.reject_times
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setRejectTimes(Integer rejectTimes) {
        this.rejectTimes = rejectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.laboratory
     *
     * @return the value of oms_order.laboratory
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getLaboratory() {
        return laboratory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.laboratory
     *
     * @param laboratory the value for oms_order.laboratory
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setLaboratory(String laboratory) {
        this.laboratory = laboratory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.remark
     *
     * @return the value of oms_order.remark
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.remark
     *
     * @param remark the value for oms_order.remark
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    private String isInterpretationReport;

    public String getIsInterpretationReport() {
        return isInterpretationReport;
    }

    public void setIsInterpretationReport(String isInterpretationReport) {
        this.isInterpretationReport = isInterpretationReport;
    }
}