package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;


public class OmsPupuDelivery implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.iid
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private String deliveryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.delivery_qty
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private Double deliveryQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.delivery_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private Date deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_delivery.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.iid
     *
     * @return the value of oms_pupu_delivery.iid
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.iid
     *
     * @param iid the value for oms_pupu_delivery.iid
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.order_no
     *
     * @return the value of oms_pupu_delivery.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.order_no
     *
     * @param orderNo the value for oms_pupu_delivery.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.delivery_no
     *
     * @return the value of oms_pupu_delivery.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.delivery_no
     *
     * @param deliveryNo the value for oms_pupu_delivery.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.delivery_qty
     *
     * @return the value of oms_pupu_delivery.delivery_qty
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public Double getDeliveryQty() {
        return deliveryQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.delivery_qty
     *
     * @param deliveryQty the value for oms_pupu_delivery.delivery_qty
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setDeliveryQty(Double deliveryQty) {
        this.deliveryQty = deliveryQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.delivery_time
     *
     * @return the value of oms_pupu_delivery.delivery_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.delivery_time
     *
     * @param deliveryTime the value for oms_pupu_delivery.delivery_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_delivery.create_time
     *
     * @return the value of oms_pupu_delivery.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_delivery.create_time
     *
     * @param createTime the value for oms_pupu_delivery.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}