package com.nh.oms.model.oms;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsPrice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.id
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private String id;

    private String channelGroupPid;

    public String getChannelGroupPid() {
        return channelGroupPid;
    }

    public void setChannelGroupPid(String channelGroupPid) {
        this.channelGroupPid = channelGroupPid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.product_code
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.price_start
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private Date priceStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.price_end
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private Date priceEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.price
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.price_sort
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private Integer priceSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.enable
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private String enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_price_system.create_time
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.id
     *
     * @return the value of oms_price_system.id
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.id
     *
     * @param id the value for oms_price_system.id
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.product_code
     *
     * @return the value of oms_price_system.product_code
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.product_code
     *
     * @param productCode the value for oms_price_system.product_code
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.price_start
     *
     * @return the value of oms_price_system.price_start
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public Date getPriceStart() {
        return priceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.price_start
     *
     * @param priceStart the value for oms_price_system.price_start
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setPriceStart(Date priceStart) {
        this.priceStart = priceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.price_end
     *
     * @return the value of oms_price_system.price_end
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public Date getPriceEnd() {
        return priceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.price_end
     *
     * @param priceEnd the value for oms_price_system.price_end
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setPriceEnd(Date priceEnd) {
        this.priceEnd = priceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.price
     *
     * @return the value of oms_price_system.price
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.price
     *
     * @param price the value for oms_price_system.price
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.price_sort
     *
     * @return the value of oms_price_system.price_sort
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public Integer getPriceSort() {
        return priceSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.price_sort
     *
     * @param priceSort the value for oms_price_system.price_sort
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setPriceSort(Integer priceSort) {
        this.priceSort = priceSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.enable
     *
     * @return the value of oms_price_system.enable
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.enable
     *
     * @param enable the value for oms_price_system.enable
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setEnable(String enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_price_system.create_time
     *
     * @return the value of oms_price_system.create_time
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_price_system.create_time
     *
     * @param createTime the value for oms_price_system.create_time
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}