package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;

public class OmsPupuCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.iid
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.id
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String deliveryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.batch_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.saleout_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String saleoutNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String pupuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_pupu_code.is_refund
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private String isRefund;

    private String rowNo;

    public String getRowNo() {
        return rowNo;
    }

    public void setRowNo(String rowNo) {
        this.rowNo = rowNo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.iid
     *
     * @return the value of oms_pupu_code.iid
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.iid
     *
     * @param iid the value for oms_pupu_code.iid
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.id
     *
     * @return the value of oms_pupu_code.id
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.id
     *
     * @param id the value for oms_pupu_code.id
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.order_no
     *
     * @return the value of oms_pupu_code.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.order_no
     *
     * @param orderNo the value for oms_pupu_code.order_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.delivery_no
     *
     * @return the value of oms_pupu_code.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.delivery_no
     *
     * @param deliveryNo the value for oms_pupu_code.delivery_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.batch_no
     *
     * @return the value of oms_pupu_code.batch_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.batch_no
     *
     * @param batchNo the value for oms_pupu_code.batch_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.saleout_no
     *
     * @return the value of oms_pupu_code.saleout_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getSaleoutNo() {
        return saleoutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.saleout_no
     *
     * @param saleoutNo the value for oms_pupu_code.saleout_no
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setSaleoutNo(String saleoutNo) {
        this.saleoutNo = saleoutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.pupu_code
     *
     * @return the value of oms_pupu_code.pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getPupuCode() {
        return pupuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.pupu_code
     *
     * @param pupuCode the value for oms_pupu_code.pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setPupuCode(String pupuCode) {
        this.pupuCode = pupuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.create_time
     *
     * @return the value of oms_pupu_code.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.create_time
     *
     * @param createTime the value for oms_pupu_code.create_time
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_pupu_code.is_refund
     *
     * @return the value of oms_pupu_code.is_refund
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public String getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_pupu_code.is_refund
     *
     * @param isRefund the value for oms_pupu_code.is_refund
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    public void setIsRefund(String isRefund) {
        this.isRefund = isRefund;
    }
}