package com.nh.oms.model.oms;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsTestResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.iid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.id
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.sampleno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String sampleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.detected_person
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String detectedPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.sex
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.birthday
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.toponymy
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String toponymy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.testid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String testid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.test_result
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String testResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.result_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String resultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.test_status
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Integer testStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.correct_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Integer correctFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.sample_type
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String sampleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.fee
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.reflo
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String reflo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.refhi
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String refhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.deviceid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.measure_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Date measureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.operator_notes
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String operatorNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.hint
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String hint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.unit
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.trayno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Integer trayno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.posno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Integer posno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.receive_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Date receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.receiver
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.check_operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private String checkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.check_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.create_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result.age
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private Integer age;

    private String imReason;    //肠原因

    private String stomachReason; //胃原因

    private String unqualifiedReason;  //不合格原因

    public String getImReason() {
        return imReason;
    }

    public void setImReason(String imReason) {
        this.imReason = imReason;
    }

    public String getStomachReason() {
        return stomachReason;
    }

    public void setStomachReason(String stomachReason) {
        this.stomachReason = stomachReason;
    }

    public String getUnqualifiedReason() {
        return unqualifiedReason;
    }

    public void setUnqualifiedReason(String unqualifiedReason) {
        this.unqualifiedReason = unqualifiedReason;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_test_result
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.iid
     *
     * @return the value of oms_test_result.iid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.iid
     *
     * @param iid the value for oms_test_result.iid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.id
     *
     * @return the value of oms_test_result.id
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.id
     *
     * @param id the value for oms_test_result.id
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.sampleno
     *
     * @return the value of oms_test_result.sampleno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getSampleno() {
        return sampleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.sampleno
     *
     * @param sampleno the value for oms_test_result.sampleno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setSampleno(String sampleno) {
        this.sampleno = sampleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.detected_person
     *
     * @return the value of oms_test_result.detected_person
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getDetectedPerson() {
        return detectedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.detected_person
     *
     * @param detectedPerson the value for oms_test_result.detected_person
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setDetectedPerson(String detectedPerson) {
        this.detectedPerson = detectedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.sex
     *
     * @return the value of oms_test_result.sex
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.sex
     *
     * @param sex the value for oms_test_result.sex
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.birthday
     *
     * @return the value of oms_test_result.birthday
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.birthday
     *
     * @param birthday the value for oms_test_result.birthday
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.toponymy
     *
     * @return the value of oms_test_result.toponymy
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getToponymy() {
        return toponymy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.toponymy
     *
     * @param toponymy the value for oms_test_result.toponymy
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setToponymy(String toponymy) {
        this.toponymy = toponymy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.testid
     *
     * @return the value of oms_test_result.testid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.testid
     *
     * @param testid the value for oms_test_result.testid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setTestid(String testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.test_result
     *
     * @return the value of oms_test_result.test_result
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.test_result
     *
     * @param testResult the value for oms_test_result.test_result
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.result_flag
     *
     * @return the value of oms_test_result.result_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getResultFlag() {
        return resultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.result_flag
     *
     * @param resultFlag the value for oms_test_result.result_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setResultFlag(String resultFlag) {
        this.resultFlag = resultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.test_status
     *
     * @return the value of oms_test_result.test_status
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Integer getTestStatus() {
        return testStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.test_status
     *
     * @param testStatus the value for oms_test_result.test_status
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setTestStatus(Integer testStatus) {
        this.testStatus = testStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.correct_flag
     *
     * @return the value of oms_test_result.correct_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Integer getCorrectFlag() {
        return correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.correct_flag
     *
     * @param correctFlag the value for oms_test_result.correct_flag
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setCorrectFlag(Integer correctFlag) {
        this.correctFlag = correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.sample_type
     *
     * @return the value of oms_test_result.sample_type
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.sample_type
     *
     * @param sampleType the value for oms_test_result.sample_type
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.fee
     *
     * @return the value of oms_test_result.fee
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.fee
     *
     * @param fee the value for oms_test_result.fee
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.reflo
     *
     * @return the value of oms_test_result.reflo
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getReflo() {
        return reflo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.reflo
     *
     * @param reflo the value for oms_test_result.reflo
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setReflo(String reflo) {
        this.reflo = reflo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.refhi
     *
     * @return the value of oms_test_result.refhi
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getRefhi() {
        return refhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.refhi
     *
     * @param refhi the value for oms_test_result.refhi
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setRefhi(String refhi) {
        this.refhi = refhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.deviceid
     *
     * @return the value of oms_test_result.deviceid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.deviceid
     *
     * @param deviceid the value for oms_test_result.deviceid
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.measure_time
     *
     * @return the value of oms_test_result.measure_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Date getMeasureTime() {
        return measureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.measure_time
     *
     * @param measureTime the value for oms_test_result.measure_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setMeasureTime(Date measureTime) {
        this.measureTime = measureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.operator
     *
     * @return the value of oms_test_result.operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.operator
     *
     * @param operator the value for oms_test_result.operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.operator_notes
     *
     * @return the value of oms_test_result.operator_notes
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getOperatorNotes() {
        return operatorNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.operator_notes
     *
     * @param operatorNotes the value for oms_test_result.operator_notes
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setOperatorNotes(String operatorNotes) {
        this.operatorNotes = operatorNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.hint
     *
     * @return the value of oms_test_result.hint
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getHint() {
        return hint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.hint
     *
     * @param hint the value for oms_test_result.hint
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setHint(String hint) {
        this.hint = hint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.unit
     *
     * @return the value of oms_test_result.unit
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.unit
     *
     * @param unit the value for oms_test_result.unit
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.trayno
     *
     * @return the value of oms_test_result.trayno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Integer getTrayno() {
        return trayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.trayno
     *
     * @param trayno the value for oms_test_result.trayno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setTrayno(Integer trayno) {
        this.trayno = trayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.posno
     *
     * @return the value of oms_test_result.posno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.posno
     *
     * @param posno the value for oms_test_result.posno
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.receive_time
     *
     * @return the value of oms_test_result.receive_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.receive_time
     *
     * @param receiveTime the value for oms_test_result.receive_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.receiver
     *
     * @return the value of oms_test_result.receiver
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.receiver
     *
     * @param receiver the value for oms_test_result.receiver
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.check_operator
     *
     * @return the value of oms_test_result.check_operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public String getCheckOperator() {
        return checkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.check_operator
     *
     * @param checkOperator the value for oms_test_result.check_operator
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setCheckOperator(String checkOperator) {
        this.checkOperator = checkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.check_time
     *
     * @return the value of oms_test_result.check_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.check_time
     *
     * @param checkTime the value for oms_test_result.check_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.create_time
     *
     * @return the value of oms_test_result.create_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.create_time
     *
     * @param createTime the value for oms_test_result.create_time
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result.age
     *
     * @return the value of oms_test_result.age
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result.age
     *
     * @param age the value for oms_test_result.age
     *
     * @mbggenerated Tue Nov 27 21:05:52 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}