package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;

public class OmsWorkorder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.iid
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private Long iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.order_no
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.sampleno
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String sampleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.workorder_type
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String workorderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.sample_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String sampleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.create_by
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.create_time
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.interpretation_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String interpretationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_workorder.remark
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.iid
     *
     * @return the value of oms_workorder.iid
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.iid
     *
     * @param iid the value for oms_workorder.iid
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.order_no
     *
     * @return the value of oms_workorder.order_no
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.order_no
     *
     * @param orderNo the value for oms_workorder.order_no
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.sampleno
     *
     * @return the value of oms_workorder.sampleno
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getSampleno() {
        return sampleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.sampleno
     *
     * @param sampleno the value for oms_workorder.sampleno
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setSampleno(String sampleno) {
        this.sampleno = sampleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.workorder_type
     *
     * @return the value of oms_workorder.workorder_type
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getWorkorderType() {
        return workorderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.workorder_type
     *
     * @param workorderType the value for oms_workorder.workorder_type
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setWorkorderType(String workorderType) {
        this.workorderType = workorderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.sample_status
     *
     * @return the value of oms_workorder.sample_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getSampleStatus() {
        return sampleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.sample_status
     *
     * @param sampleStatus the value for oms_workorder.sample_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setSampleStatus(String sampleStatus) {
        this.sampleStatus = sampleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.status
     *
     * @return the value of oms_workorder.status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.status
     *
     * @param status the value for oms_workorder.status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.create_by
     *
     * @return the value of oms_workorder.create_by
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.create_by
     *
     * @param createBy the value for oms_workorder.create_by
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.create_time
     *
     * @return the value of oms_workorder.create_time
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.create_time
     *
     * @param createTime the value for oms_workorder.create_time
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.interpretation_status
     *
     * @return the value of oms_workorder.interpretation_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getInterpretationStatus() {
        return interpretationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.interpretation_status
     *
     * @param interpretationStatus the value for oms_workorder.interpretation_status
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setInterpretationStatus(String interpretationStatus) {
        this.interpretationStatus = interpretationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_workorder.remark
     *
     * @return the value of oms_workorder.remark
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_workorder.remark
     *
     * @param remark the value for oms_workorder.remark
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}