package com.nh.oms.model.oms;

import java.io.Serializable;
import java.util.Date;

public class ResultDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.iid
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private Integer iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.result_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String resultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.product_name
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.test_item_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String testItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.test_result
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String testResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.sample
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private String sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_test_result_detail.create_time
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_test_result_detail
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.iid
     *
     * @return the value of oms_test_result_detail.iid
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.iid
     *
     * @param iid the value for oms_test_result_detail.iid
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.id
     *
     * @return the value of oms_test_result_detail.id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.id
     *
     * @param id the value for oms_test_result_detail.id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.result_id
     *
     * @return the value of oms_test_result_detail.result_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.result_id
     *
     * @param resultId the value for oms_test_result_detail.result_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setResultId(String resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.product_name
     *
     * @return the value of oms_test_result_detail.product_name
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.product_name
     *
     * @param productName the value for oms_test_result_detail.product_name
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.test_item_id
     *
     * @return the value of oms_test_result_detail.test_item_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getTestItemId() {
        return testItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.test_item_id
     *
     * @param testItemId the value for oms_test_result_detail.test_item_id
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setTestItemId(String testItemId) {
        this.testItemId = testItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.test_result
     *
     * @return the value of oms_test_result_detail.test_result
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.test_result
     *
     * @param testResult the value for oms_test_result_detail.test_result
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.sample
     *
     * @return the value of oms_test_result_detail.sample
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.sample
     *
     * @param sample the value for oms_test_result_detail.sample
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setSample(String sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_test_result_detail.create_time
     *
     * @return the value of oms_test_result_detail.create_time
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_test_result_detail.create_time
     *
     * @param createTime the value for oms_test_result_detail.create_time
     *
     * @mbggenerated Wed Nov 21 17:45:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}