package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsChannelGroup;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface OmsChannelGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    int insert(OmsChannelGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    int insertSelective(OmsChannelGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    OmsChannelGroup selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    int updateByPrimaryKeySelective(OmsChannelGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_channel_group
     *
     * @mbggenerated Mon Nov 12 10:33:32 CST 2018
     */
    int updateByPrimaryKey(OmsChannelGroup record);

    /**
     * 查询数据是否存在
     * @param pids
     * @return
     */
    List<String> isExists(@Param("pids") Set<String> pids);

    /**
     * 批量新增
     * @param list
     */
    void batchInsert( @Param("omsChannelGroup") List<OmsChannelGroup> list);
}