package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsExternalInterfaceLog;

public interface OmsExternalInterfaceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_external_interface_log
     *
     * @mbggenerated Fri Jan 18 18:09:32 CST 2019
     */
    int insert(OmsExternalInterfaceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_external_interface_log
     *
     * @mbggenerated Fri Jan 18 18:09:32 CST 2019
     */
    int insertSelective(OmsExternalInterfaceLog record);
}