package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsOrder;
import com.nh.oms.model.oms.OmsOrderDetail;
import com.nh.oms.transform.OrderReportInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OmsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    int insert(OmsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    int insertSelective(OmsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    OmsOrder selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    int updateByPrimaryKeySelective(OmsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Tue Nov 20 13:01:06 CST 2018
     */
    int updateByPrimaryKey(OmsOrder record);

    int updateByOrderNo(List<OmsOrder> omsOrderList);

    List<OrderReportInfo> getOrderForTaiKang();

    int updatePolicyNoById(@Param("id") String id, @Param("policyNo") String policyNo);

    /**
     * 更新订单主表状态为已发货
     * @param orderDetailsList
     */
    void updateOrderStateByOrderNo(@Param("orderList") List<OmsOrderDetail> orderDetailsList);

    /**
     * add by xujingjing at 2019-01-03 根据订单号获取订单信息
     * 用于获取报告时，发送短信功能
     */
    OmsOrder getOmsOrderByOrderNo(String orderno);

    int updateReportStateByOrderNo(String orderNo);

}