package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsOrderSyncException;

public interface OmsOrderSyncExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    int insert(OmsOrderSyncException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    int insertSelective(OmsOrderSyncException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    OmsOrderSyncException selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    int updateByPrimaryKeySelective(OmsOrderSyncException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_sync_exception
     *
     * @mbggenerated Wed Nov 14 20:53:09 CST 2018
     */
    int updateByPrimaryKey(OmsOrderSyncException record);
}