package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsPupuCode;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OmsPupuCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    int insert(OmsPupuCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    int insertSelective(OmsPupuCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    OmsPupuCode selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    int updateByPrimaryKeySelective(OmsPupuCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_code
     *
     * @mbggenerated Tue Nov 20 19:19:20 CST 2018
     */
    int updateByPrimaryKey(OmsPupuCode record);

    int bulkInsertPuPuCodeInfo(List<OmsPupuCode> list);

    List<OmsPupuCode> getModelByDeliveryNo(@Param("deliveryNo") String deliveryNo, @Param("rowNo") String rowNo);

    List<OmsPupuCode> getModelBySaleOutNo(@Param("saleOutNo") String saleOutNo, @Param("rowNo") String rowNo);

    /**
     * 发货时
     * 噗噗码为空是需要插入到oms_pupu_code表中
     * @param omsPupuCode
     */
    void insertOtcPupu(OmsPupuCode omsPupuCode);

    /**
     * 根据噗噗管的订单号+行号+批次号判断是否唯一
     * @param s
     */
    int findByNo(@Param("No") String s);

    int updateByOrderNo(OmsPupuCode omsPupuCode);
}