package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsPupuSaleout;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface OmsPupuSaleoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    int insert(OmsPupuSaleout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    int insertSelective(OmsPupuSaleout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    OmsPupuSaleout selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    int updateByPrimaryKeySelective(OmsPupuSaleout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_saleout
     *
     * @mbggenerated Tue Nov 20 19:19:52 CST 2018
     */
    int updateByPrimaryKey(OmsPupuSaleout record);

    public void batchInsertSaleOut(List<OmsPupuSaleout> saleouts) ;

    /**
     * 更新出库单号
     * @param saleoutNo
     * @param saleoutQty
     */
    public void updateSaleOutQty(@Param("orderNo") String orderNo, @Param("saleoutNo")String saleoutNo, @Param("saleoutQty") BigDecimal saleoutQty);

    int selectBySaleOutNo(@Param("saleOutNo")String saleOutNo, @Param("orderNo")String orderNo);
}