package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsPrice;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface OmsPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    int insert(OmsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    int insertSelective(OmsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    OmsPrice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    int updateByPrimaryKeySelective(OmsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_price_system
     *
     * @mbggenerated Tue Nov 06 20:58:53 CST 2018
     */
    int updateByPrimaryKey(OmsPrice record);

    /**
     * 批量插入
     * @param omsPrices
     * @return
     */
    int batchInsert( @Param("omsPrices") List<OmsPrice> omsPrices);

    /**
     * 校验产品编码是否存在
     * @param productCodes
     * @return
     */
    List<String> isExists(@Param("productCodes") Set<String> productCodes);

    /**
     * 查询渠道分组是否存在
     * @param groupPids
     * @return
     */
    List<String>  isGroupPidExists(@Param("groupPids")Set<String> groupPids);

    /**
     *数据是否已经存在
     * @param ids
     * @return
     */
    List<String> isIdExists(@Param("ids")Set<String> ids);

    /**
     * 根据id+groupId 进行更新
     * @param price
     * @return
     */
    int updateByIdGroupId(OmsPrice price);

}