package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsPupuDelivery;
import com.nh.oms.model.oms.OmsPupuDeliveryExt;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OmsPupuDeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    int insert(OmsPupuDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    int insertSelective(OmsPupuDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    OmsPupuDelivery selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    int updateByPrimaryKeySelective(OmsPupuDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pupu_delivery
     *
     * @mbggenerated Tue Nov 20 19:19:39 CST 2018
     */
    int updateByPrimaryKey(OmsPupuDelivery record);



    /**
     * 批量保存出库信息
     * @param deliverys
     */
    void batchInsertDelivery(OmsPupuDeliveryExt deliverys);

    /**
     * 更新订单出库数量
     * @param deliveryNo
     * @param deliveryQty
     */
    void updateDeliveryQty(@Param("orderNo") String deliveryNo,@Param("deliveryQty") Double deliveryQty);


    List<String> existsDeliveryNo(@Param("deliveryList") List<OmsPupuDeliveryExt> deliveryList );

    /**
     * 新增噗噗管记录后
     * 更新状态
     * @param orderNo
     */
    void updateDeliveryStatus(@Param("orderNo") String orderNo);

}