package com.nh.oms.dao.oms;

import com.nh.oms.model.oms.OmsWorkorder;

public interface OmsWorkorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    int insert(OmsWorkorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    int insertSelective(OmsWorkorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    OmsWorkorder selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    int updateByPrimaryKeySelective(OmsWorkorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_workorder
     *
     * @mbggenerated Thu Jan 03 15:27:03 CST 2019
     */
    int updateByPrimaryKey(OmsWorkorder record);
}